"""3. modify invoice detail table

Revision ID: 323269e09494
Revises: 249ea89d7923
Create Date: 2023-09-10 23:39:23.047907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323269e09494'
down_revision: Union[str, None] = '249ea89d7923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('type', sa.Integer(), server_default='0', nullable=True))
    op.add_column('invoice_detail', sa.Column('price', sa.Double(), nullable=False))
    op.add_column('invoice_detail', sa.Column('total', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_detail', 'total')
    op.drop_column('invoice_detail', 'price')
    op.drop_column('invoice', 'type')
    # ### end Alembic commands ###
